import type { ColumnNode, DataType, SchemaNode, TableNode } from '../../ast/types.js';
import type { Emitter } from '../emitter.interface.js';

export interface OpenApiEmitterOptions {
  title?: string;
  description?: string;
  serverUrl?: string;
}

export interface OpenApiSpec {
  openapi: string;
  info: {
    title: string;
    version: string;
    description: string;
  };
  servers?: { url: string; description?: string }[];
  components: {
    securitySchemes: Record<string, any>;
    schemas: Record<string, any>;
  };
  security: { bearerAuth: string[] }[];
  paths: Record<string, any>;
}

export class OpenApiEmitter implements Emitter<OpenApiSpec, OpenApiEmitterOptions> {
  readonly name = 'OpenApiEmitter';

  emit(schema: SchemaNode, options: OpenApiEmitterOptions = {}): OpenApiSpec {
    const {
      title = 'Clous Generated API',
      description = 'Dynamic REST API generated by Clous BaaS Engine',
      serverUrl,
    } = options;

    const spec: OpenApiSpec = {
      openapi: '3.0.3',
      info: {
        title,
        version: schema.version,
        description,
      },
      servers: serverUrl ? [{ url: serverUrl }] : [],
      components: {
        securitySchemes: {
          bearerAuth: {
            type: 'http',
            scheme: 'bearer',
            bearerFormat: 'JWT',
            description: 'Enter your JWT token to authenticate',
          },
        },
        schemas: {},
      },
      security: [{ bearerAuth: [] }],
      paths: {},
    };

    for (const table of schema.tables) {
      const pascalName = this.toPascalCase(table.name);

      // 1. Schemas
      const rowProperties: Record<string, any> = {};
      const insertProperties: Record<string, any> = {};
      const updateProperties: Record<string, any> = {};
      const requiredInsert: string[] = [];

      for (const col of table.columns) {
        const jsonSchemaType = this.mapTypeToJsonSchema(col.type);
        rowProperties[col.name] = {
          ...jsonSchemaType,
          nullable: col.isNullable,
        };

        insertProperties[col.name] = {
          ...jsonSchemaType,
          nullable: col.isNullable,
        };

        updateProperties[col.name] = {
          ...jsonSchemaType,
          nullable: col.isNullable,
        };

        const isOptionalInInsert =
          col.defaultValue !== undefined ||
          col.type === 'serial' ||
          col.isNullable;

        if (!isOptionalInInsert) {
          requiredInsert.push(col.name);
        }
      }

      spec.components.schemas[`${pascalName}Row`] = {
        type: 'object',
        properties: rowProperties,
      };

      spec.components.schemas[`${pascalName}Insert`] = {
        type: 'object',
        properties: insertProperties,
        required: requiredInsert.length > 0 ? requiredInsert : undefined,
      };

      spec.components.schemas[`${pascalName}Update`] = {
        type: 'object',
        properties: updateProperties,
      };

      // 2. Paths
      const listPath = `/api/${table.name}`;
      const itemPath = `/api/${table.name}/{id}`;

      spec.paths[listPath] = {
        get: {
          tags: [table.name],
          summary: `List rows from ${table.name}`,
          parameters: [
            {
              name: 'page',
              in: 'query',
              schema: { type: 'integer', default: 1 },
              description: 'Page number for pagination',
            },
            {
              name: 'limit',
              in: 'query',
              schema: { type: 'integer', default: 20 },
              description: 'Maximum items per page',
            },
            {
              name: 'sort',
              in: 'query',
              schema: { type: 'string' },
              description: 'Column to sort by',
            },
            {
              name: 'order',
              in: 'query',
              schema: { type: 'string', enum: ['asc', 'desc'], default: 'asc' },
              description: 'Sort direction',
            },
          ],
          responses: {
            '200': {
              description: 'Successful query',
              content: {
                'application/json': {
                  schema: {
                    type: 'object',
                    properties: {
                      data: {
                        type: 'array',
                        items: {
                          $ref: `#/components/schemas/${pascalName}Row`,
                        },
                      },
                      pagination: {
                        type: 'object',
                        properties: {
                          total: { type: 'integer' },
                          page: { type: 'integer' },
                          limit: { type: 'integer' },
                          totalPages: { type: 'integer' },
                        },
                      },
                    },
                  },
                },
              },
            },
          },
        },
        post: {
          tags: [table.name],
          summary: `Insert new row into ${table.name}`,
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: {
                  $ref: `#/components/schemas/${pascalName}Insert`,
                },
              },
            },
          },
          responses: {
            '201': {
              description: 'Row created',
              content: {
                'application/json': {
                  schema: {
                    $ref: `#/components/schemas/${pascalName}Row`,
                  },
                },
              },
            },
            '400': { description: 'Bad Request / Validation Error' },
          },
        },
      };

      spec.paths[itemPath] = {
        get: {
          tags: [table.name],
          summary: `Get single ${table.name} row by ID`,
          parameters: [
            {
              name: 'id',
              in: 'path',
              required: true,
              schema: { type: 'string' },
            },
          ],
          responses: {
            '200': {
              description: 'Item found',
              content: {
                'application/json': {
                  schema: {
                    $ref: `#/components/schemas/${pascalName}Row`,
                  },
                },
              },
            },
            '404': { description: 'Row not found or denied by RLS' },
          },
        },
        patch: {
          tags: [table.name],
          summary: `Update ${table.name} row by ID`,
          parameters: [
            {
              name: 'id',
              in: 'path',
              required: true,
              schema: { type: 'string' },
            },
          ],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: {
                  $ref: `#/components/schemas/${pascalName}Update`,
                },
              },
            },
          },
          responses: {
            '200': {
              description: 'Updated item',
              content: {
                'application/json': {
                  schema: {
                    $ref: `#/components/schemas/${pascalName}Row`,
                  },
                },
              },
            },
            '404': { description: 'Row not found or denied by RLS' },
          },
        },
        delete: {
          tags: [table.name],
          summary: `Delete ${table.name} row by ID`,
          parameters: [
            {
              name: 'id',
              in: 'path',
              required: true,
              schema: { type: 'string' },
            },
          ],
          responses: {
            '200': {
              description: 'Deleted item',
              content: {
                'application/json': {
                  schema: {
                    $ref: `#/components/schemas/${pascalName}Row`,
                  },
                },
              },
            },
            '404': { description: 'Row not found or denied by RLS' },
          },
        },
      };
    }

    return spec;
  }

  private mapTypeToJsonSchema(type: DataType): { type: string; format?: string } {
    switch (type) {
      case 'uuid':
        return { type: 'string', format: 'uuid' };
      case 'text':
      case 'varchar':
        return { type: 'string' };
      case 'integer':
      case 'serial':
        return { type: 'integer' };
      case 'bigint':
      case 'float':
        return { type: 'number' };
      case 'boolean':
        return { type: 'boolean' };
      case 'timestamp':
      case 'timestamptz':
        return { type: 'string', format: 'date-time' };
      case 'jsonb':
        return { type: 'object' };
      default:
        return { type: 'string' };
    }
  }

  private toPascalCase(str: string): string {
    return str
      .replace(/(?:^|_|-)(\w)/g, (_, c) => c.toUpperCase())
      .replace(/[^a-zA-Z0-9]/g, '');
  }
}
