import type {
  ColumnNode,
  DataType,
  SchemaNode,
  TableNode,
} from '../../ast/types.js';
import type { Emitter } from '../emitter.interface.js';

export interface TsEmitterOptions {
  includeHeader?: boolean;
}

export class TsTypeEmitter implements Emitter<string, TsEmitterOptions> {
  readonly name = 'TsTypeEmitter';

  emit(schema: SchemaNode, options: TsEmitterOptions = {}): string {
    const { includeHeader = true } = options;
    const lines: string[] = [];

    if (includeHeader) {
      lines.push(
        `/**`,
        ` * Generated by Clous Core Engine (v${schema.version})`,
        ` * Timestamp: ${new Date().toISOString()}`,
        ` * WARNING: Do not edit directly. Changes will be overwritten.`,
        ` */`,
        ''
      );
    }

    // Helper Json type
    lines.push(
      `export type Json =`,
      `  | string`,
      `  | number`,
      `  | boolean`,
      `  | null`,
      `  | { [key: string]: Json | undefined }`,
      `  | Json[];`,
      ''
    );

    // Emit interfaces for each table
    for (const table of schema.tables) {
      const pascalName = this.toPascalCase(table.name);

      // Row type
      lines.push(`export interface ${pascalName}Row {`);
      for (const col of table.columns) {
        const tsType = this.mapColumnTypeToTs(col.type);
        const nullability = col.isNullable ? ' | null' : '';
        lines.push(`  ${col.name}: ${tsType}${nullability};`);
      }
      lines.push('}', '');

      // Insert type
      lines.push(`export interface ${pascalName}Insert {`);
      for (const col of table.columns) {
        const tsType = this.mapColumnTypeToTs(col.type);
        const isOptional =
          col.defaultValue !== undefined ||
          col.type === 'serial' ||
          col.isNullable;
        const optMark = isOptional ? '?' : '';
        const nullability = col.isNullable ? ' | null' : '';
        lines.push(`  ${col.name}${optMark}: ${tsType}${nullability};`);
      }
      lines.push('}', '');

      // Update type
      lines.push(`export interface ${pascalName}Update {`);
      for (const col of table.columns) {
        const tsType = this.mapColumnTypeToTs(col.type);
        const nullability = col.isNullable ? ' | null' : '';
        lines.push(`  ${col.name}?: ${tsType}${nullability};`);
      }
      lines.push('}', '');
    }

    // Database schema mapping
    lines.push('export interface Database {');
    for (const table of schema.tables) {
      const pascalName = this.toPascalCase(table.name);
      lines.push(`  ${table.name}: {`);
      lines.push(`    Row: ${pascalName}Row;`);
      lines.push(`    Insert: ${pascalName}Insert;`);
      lines.push(`    Update: ${pascalName}Update;`);
      lines.push(`  };`);
    }
    lines.push('}', '');

    return lines.join('\n');
  }

  private mapColumnTypeToTs(type: DataType): string {
    switch (type) {
      case 'uuid':
      case 'text':
      case 'varchar':
        return 'string';
      case 'integer':
      case 'float':
      case 'serial':
        return 'number';
      case 'bigint':
        return 'bigint | number';
      case 'boolean':
        return 'boolean';
      case 'timestamp':
      case 'timestamptz':
        return 'string | Date';
      case 'jsonb':
        return 'Json';
      default:
        return 'unknown';
    }
  }

  private toPascalCase(str: string): string {
    return str
      .replace(/(?:^|_|-)(\w)/g, (_, c) => c.toUpperCase())
      .replace(/[^a-zA-Z0-9]/g, '');
  }
}
