import type {
  ColumnNode,
  DataType,
  DefaultValue,
  IndexNode,
  PolicyNode,
  SchemaNode,
  TableNode,
} from '../../ast/types.js';
import type { Emitter } from '../emitter.interface.js';

export interface PostgresEmitterOptions {
  includeExtensions?: boolean;
  includeAuthHelpers?: boolean;
  dropIfExists?: boolean;
  enableRlsByDefault?: boolean;
}

export class PostgresSqlEmitter
  implements Emitter<string, PostgresEmitterOptions>
{
  readonly name = 'PostgresSqlEmitter';

  emit(schema: SchemaNode, options: PostgresEmitterOptions = {}): string {
    const {
      includeExtensions = true,
      includeAuthHelpers = true,
      dropIfExists = false,
      enableRlsByDefault = true,
    } = options;

    const statements: string[] = [];

    // Header comment
    statements.push(
      `-- Generated by Clous Core Engine (v${schema.version})`,
      `-- Timestamp: ${new Date().toISOString()}`,
      ''
    );

    // Extensions
    if (includeExtensions) {
      const hasUuid = schema.tables.some((t) =>
        t.columns.some((c) => c.type === 'uuid')
      );
      if (hasUuid) {
        statements.push('CREATE EXTENSION IF NOT EXISTS "pgcrypto";');
        statements.push('');
      }
    }

    // Auth Helpers for RLS
    if (includeAuthHelpers) {
      statements.push(
        '-- Clous Auth Schema & RLS Helper Functions',
        'CREATE SCHEMA IF NOT EXISTS auth;',
        '',
        'CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid AS $$',
        "  SELECT NULLIF(current_setting('request.jwt.claim.sub', true), '')::uuid;",
        '$$ LANGUAGE sql STABLE;',
        '',
        'CREATE OR REPLACE FUNCTION auth.role() RETURNS text AS $$',
        "  SELECT COALESCE(NULLIF(current_setting('request.jwt.claim.role', true), ''), 'anon');",
        '$$ LANGUAGE sql STABLE;',
        '',
        'CREATE OR REPLACE FUNCTION auth.email() RETURNS text AS $$',
        "  SELECT NULLIF(current_setting('request.jwt.claim.email', true), '');",
        '$$ LANGUAGE sql STABLE;',
        ''
      );
    }

    // Optional drops
    if (dropIfExists) {
      // Drop in reverse order to respect foreign key dependencies
      for (const table of [...schema.tables].reverse()) {
        statements.push(`DROP TABLE IF EXISTS "${table.name}" CASCADE;`);
      }
      statements.push('');
    }

    // Create Tables
    for (const table of schema.tables) {
      statements.push(this.emitCreateTable(table));
      statements.push('');

      // Indexes
      if (table.indexes.length > 0) {
        for (const idx of table.indexes) {
          statements.push(this.emitCreateIndex(table.name, idx));
        }
        statements.push('');
      }

      // Row Level Security (RLS)
      const shouldEnableRls =
        enableRlsByDefault || table.policies.length > 0;

      if (shouldEnableRls) {
        statements.push(
          `ALTER TABLE "${table.name}" ENABLE ROW LEVEL SECURITY;`
        );

        for (const policy of table.policies) {
          statements.push(this.emitCreatePolicy(table.name, policy));
        }
        statements.push('');
      }
    }

    return statements.join('\n').trim() + '\n';
  }

  private emitCreateTable(table: TableNode): string {
    const lines: string[] = [];
    lines.push(`CREATE TABLE IF NOT EXISTS "${table.name}" (`);

    const columnDefs: string[] = table.columns.map(
      (col) => `  ${this.emitColumn(col)}`
    );

    lines.push(columnDefs.join(',\n'));
    lines.push(');');

    return lines.join('\n');
  }

  private emitColumn(col: ColumnNode): string {
    const parts: string[] = [`"${col.name}"`, this.mapDataType(col)];

    if (col.isPrimaryKey) {
      parts.push('PRIMARY KEY');
    }

    if (!col.isNullable && !col.isPrimaryKey) {
      parts.push('NOT NULL');
    }

    if (col.isUnique && !col.isPrimaryKey) {
      parts.push('UNIQUE');
    }

    if (col.defaultValue !== undefined) {
      parts.push(`DEFAULT ${this.formatDefaultValue(col.defaultValue)}`);
    }

    if (col.references) {
      const { table, column, onDelete, onUpdate } = col.references;
      let fk = `REFERENCES "${table}" ("${column}")`;
      if (onDelete) {
        fk += ` ON DELETE ${onDelete.toUpperCase()}`;
      }
      if (onUpdate) {
        fk += ` ON UPDATE ${onUpdate.toUpperCase()}`;
      }
      parts.push(fk);
    }

    return parts.join(' ');
  }

  private mapDataType(col: ColumnNode): string {
    switch (col.type) {
      case 'uuid':
        return 'UUID';
      case 'text':
        return 'TEXT';
      case 'varchar':
        return col.length ? `VARCHAR(${col.length})` : 'VARCHAR';
      case 'integer':
        return 'INTEGER';
      case 'bigint':
        return 'BIGINT';
      case 'boolean':
        return 'BOOLEAN';
      case 'timestamp':
        return 'TIMESTAMP WITHOUT TIME ZONE';
      case 'timestamptz':
        return 'TIMESTAMP WITH TIME ZONE';
      case 'jsonb':
        return 'JSONB';
      case 'float':
        return 'DOUBLE PRECISION';
      case 'serial':
        return 'SERIAL';
      default:
        return 'TEXT';
    }
  }

  private formatDefaultValue(val: DefaultValue): string {
    if (typeof val === 'string') {
      return `'${val.replace(/'/g, "''")}'`;
    }
    if (typeof val === 'number') {
      return `${val}`;
    }
    if (typeof val === 'boolean') {
      return val ? 'TRUE' : 'FALSE';
    }
    if (typeof val === 'object' && val.kind === 'raw') {
      // Allowlist: Only permit safe, known SQL expressions.
      // This prevents DDL injection via crafted raw default values.
      const safeExpressions = /^(now\(\)|gen_random_uuid\(\)|current_timestamp|true|false|\d+(\.\d+)?|uuid_generate_v4\(\)|CURRENT_DATE|CURRENT_TIME)$/i;
      if (!safeExpressions.test(val.expression.trim())) {
        throw new Error(
          `Unsafe raw SQL expression in default value: "${val.expression}". ` +
          `Only whitelisted expressions are allowed (e.g. now(), gen_random_uuid()).`
        );
      }
      return val.expression;
    }
    return `'${String(val)}'`;
  }

  private emitCreateIndex(tableName: string, index: IndexNode): string {
    const idxName =
      index.name ??
      `idx_${tableName}_${index.columns.join('_')}`;
    const uniqueClause = index.unique ? 'UNIQUE ' : '';
    const methodClause = index.method ? `USING ${index.method} ` : '';
    const columns = index.columns.map((c) => `"${c}"`).join(', ');

    return `CREATE ${uniqueClause}INDEX IF NOT EXISTS "${idxName}" ON "${tableName}" ${methodClause}(${columns});`;
  }

  private emitCreatePolicy(tableName: string, policy: PolicyNode): string {
    const parts: string[] = [
      `CREATE POLICY "${policy.name}" ON "${tableName}"`,
      `  FOR ${policy.for.toUpperCase()}`,
    ];

    if (policy.to) {
      parts.push(`  TO ${policy.to}`);
    }

    if (policy.using) {
      parts.push(`  USING (${policy.using})`);
    }

    if (policy.withCheck) {
      parts.push(`  WITH CHECK (${policy.withCheck})`);
    }

    return parts.join('\n') + ';';
  }
}
